Fix new line conversion corner case
horde/Stream_Filter pull request #2
Opened 2022-08-29 14:45 UTC by bsod85

2022-11-14 20:29 UTC, yunosh requested changes

2022-11-14 20:29 UTC, yunosh commented on lib/Horde/Stream/Filter/Eol.php
> -    protected $_split = null;
Why did you remove the $_split property?

2022-11-14 20:29 UTC, yunosh commented on test/Horde/Stream/Filter/EolTest.php
> -            array("\r", "ABCDEFGHI"),
These two tests got messed up.

2022-11-14 20:29 UTC, yunosh commented on test/Horde/Stream/Filter/EolTest.php
> +        $test = str_repeat(str_repeat("A", 1) . "\r\n", 4000);
str_repeat(...,1) doesn't make much sense.

2025-04-07 13:40 UTC, bsod85 commented on lib/Horde/Stream/Filter/Eol.php
> -    protected $_split = null;
The previous implementation saved the target EOL first character in this property. To my understanding this was wrong as we are searching for source EOLs.
My implementation uses the _prependNext property to keep track of a carriage return at the end of a bucket when we are searching for CR+LF EOLs.

2025-04-07 13:40 UTC, bsod85 commented on test/Horde/Stream/Filter/EolTest.php
> -            array("\r", "ABCDEFGHI"),
I changed the strings to use escaped notation for carriage returns.

2025-04-07 13:41 UTC, bsod85 commented on test/Horde/Stream/Filter/EolTest.php
> +        $test = str_repeat(str_repeat("A", 1) . "\r\n", 4000);
That was a left over from the developing phase. Fixed. Thanks

2025-04-07 13:56 UTC, bsod85 commented on test/Horde/Stream/Filter/EolTest.php
> +        $test = str_repeat("A\r\n", 4000);
this test string needs to be bigger than a stream bucket and the carriage return needs to be at the end of a bucket

2026-04-02 10:51 UTC, ralflang commented
Thank you @bsod85 for this excellent bug fix and your patience over the past 3+ years!

Your analysis was spot-on: the original 2013 fix for Bug #12673 tracked the TARGET EOL's first character but needed to track the SOURCE EOL split. Your solution correctly saves the boundary-spanning `\r` and prepends it to the next bucket for complete processing.

We've redirected your changes to feature branch `fix/eol-crlf-bucket-boundary` where we'll add minor modernizations (array syntax, documentation updates, copyright year) and additional test coverage before merging to FRAMEWORK_6_0.

Changes being applied:
- ✅ Your core fix (all 3 commits cherry-picked)
- ✅ Modernize to current Horde coding standards
- ✅ Enhanced documentation
- ✅ Additional edge case tests
- ✅ Copyright update to 2026

This will be merged to the production FRAMEWORK_6_0 branch shortly. Thanks again for your contribution!

2026-04-02 10:51 UTC, ralflang commented
Accepting into a feature branch which includes your changes plus minor modernizations. Will merge to FRAMEWORK_6_0 after final review.

2026-04-02 11:08 UTC, merged

2026-04-02 11:37 UTC, bsod85 commented
Thank you very much!